### ISSUE TITLE
Checking inventory service for coverage causes TypeError

### ISSUE THREAD

**Issue by saebyn** [mathuin/TopoMC#1]
./GetDataset.py --region Property --ymax 64.662840 --ymin 64.6419 --xmin -150.3105 --xmax -150.2931

Retrieving new dataset Property...
Checking inventory service for coverage.
Traceback (most recent call last):
  File "./GetDataset.py", line 351, in <module>
    sys.exit(main(sys.argv))
  File "./GetDataset.py", line 338, in main
    print "Inventory service has the following product IDs: %s" % ','.join([elem[0] for elem in productIDs])
TypeError: 'NoneType' object is not subscriptable

**Comment by mathuin** [comment]
TopoMC does not yet support Alaska or Hawaii. I am currently testing Alaska support now and hope to have it working for next week.  If you are impatient, add 'NAK' to elevationIDs and 'L04' to landcoverIDs in dataset.py and try again!

Jack.

**Comment by mathuin** [comment]
I have checked in to the 'develop' branch a fix for the AK/HI problem.  I will roll out a new release next week and move it into the 'master' branch at that time.  Give the checked-in code a chance by typing 'git pull && git checkout develop' and then run your ./GetDataset.py line again.  Thanks for posting the issue!

**Comment by saebyn** [comment]
Thanks! It's working now.
