### ISSUE TITLE
AttributeError: CLIDT instance has no attribute 'canCL'

### ISSUE THREAD

**Issue by thegundam** [mathuin/TopoMC#12]
walnut@Tree:~/TopoMC$ ./PrepRegion.py --name Park
Preparing region Park...
Traceback (most recent call last):
  File "./PrepRegion.py", line 26, in <module>
    sys.exit(main())
  File "./PrepRegion.py", line 23, in main
    myRegion.buildmap(args.doOCL)
  File "/home/walnut/TopoMC/region.py", line 590, in buildmap
    crustarray = newcrust()
  File "/home/walnut/TopoMC/crust.py", line 26, in **call**
    retval = self.clidt()
  File "/home/walnut/TopoMC/clidt.py", line 116, in **call**
    if self.wantCL and self.canCL:
AttributeError: CLIDT instance has no attribute 'canCL'

**Comment by mathuin** [comment]
Interesting.  What happens when you run "./PrepRegion.py --name Park --disable-opencl" ?

Also, if you could add a print statement before line 78 saying something and one before line 82 saying something else, I'd love to know which one prints when you run it again without --disable-opencl.

Thanks!

Jack.

**Comment by thegundam** [comment]
It runs without any errors when i use --disable-opencl.

You didn't specify which file to edit, so I assumed that you meant clidt.py. I apologize if that's not what you wanted. Just let me know, and I will try again. 

```
    def __init__(self, coords, values, base, wantCL=True, split=None, nnear=None, majority=True):
        self.coords = np.asarray(coords, dtype=np.int32)
        self.values = np.asarray(values, dtype=np.int32)
        self.base = np.asarray(base, dtype=np.int32)
        lencoords = self.coords.shape[0]
        lenvalues = self.values.shape[0]
        assert lencoords == lenvalues, "lencoords does not equal lenvalues"

        self.wantCL = wantCL
        if hasCL == True and self.wantCL == True:
            if split == None:
                self.split = CLIDT.OpenCLmaxsize
            else:
                self.split = split
            try:
                self.ctx = cl.create_some_context()
                self.queue = cl.CommandQueue(self.ctx)
                filestr = ''.join(open('idt.cl', 'r').readlines())
                self.program = cl.Program(self.ctx, filestr).build()
                self.coordindices = self.genindices(self.coords)
                self.baseindices = self.genindices(self.base)
                print "This message comes before line 78"
                self.canCL = True
            # FIXME: specify an exception type
            except:
                print "warning: unable to use pyopencl, defaulting to Invdisttree"
                print "This message comes before line 82"
                self.canCL = False

        if nnear == None:
            self.nnear = np.int32(CLIDT.nnear)
        else:
            self.nnear = np.int32(nnear)

        self.usemajority = np.int32(1 if majority else 0)

```

And the result is:

> walnut@Tree:~/TopoMC$ ./PrepRegion.py --name Park
> Preparing region Park...
> Traceback (most recent call last):
>  File "./PrepRegion.py", line 26, in <module>
>    sys.exit(main())
>  File "./PrepRegion.py", line 23, in main
>    myRegion.buildmap(args.doOCL)
>  File "/home/walnut/TopoMC/region.py", line 590, in buildmap
>    crustarray = newcrust()
>  File "/home/walnut/TopoMC/crust.py", line 26, in **call**
>    retval = self.clidt()
>  File "/home/walnut/TopoMC/clidt.py", line 118, in **call**
>    if self.wantCL and self.canCL:
> AttributeError: CLIDT instance has no attribute 'canCL'

**Comment by mathuin** [comment]
That was exactly what I wanted, thank you.

Have you installed the OpenCL software?  Do you know that it works?  I have downloaded and installed pyopencl-2011.2, and when I run the tests, they pass:

```
jmt@nala:~$ python /home/jmt/Downloads/pyopencl-2011.2/test/test_clmath.py 
============================= test session starts ==============================
platform linux2 -- Python 2.7.3 -- pytest-2.2.3
collected 20 items 

Downloads/pyopencl-2011.2/test/test_clmath.py ....................

========================== 20 passed in 8.33 seconds ===========================
```

I'd like to know if your system passes the tests too.

Also, if you could try changing that section of clidt.py to look like this:

``` python
        self.wantCL = wantCL
        if hasCL == True and self.wantCL == True:
            if split == None:
                self.split = CLIDT.OpenCLmaxsize
            else:
                self.split = split
            try:
                self.ctx = cl.create_some_context()
                self.queue = cl.CommandQueue(self.ctx)
                filestr = ''.join(open('idt.cl', 'r').readlines())
                self.program = cl.Program(self.ctx, filestr).build()
                self.coordindices = self.genindices(self.coords)
                self.baseindices = self.genindices(self.base)
                self.canCL = True
            # FIXME: specify an exception type
            except:
                print "warning: unable to use pyopencl, defaulting to Invdisttree"
                self.canCL = False
        else:
            self.canCL = False
```

If this solves your problem, I'll commit the change to the develop branch.

Thanks again for responding so quickly!

Jack.

**Comment by thegundam** [comment]
Apparently opencl does not work with the onboard video (intel) in that system. I've been putting off replacing the dead graphics card, but at least now I have an excuse to buy one.

No more errors after making the change.
