### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by thehighpander** [mathuin/TopoMC#2]
C:\Users\Chaska\Desktop\TopoMC\TopoMC>GetDataset.py --region Milford --ymax 39.230 --ymin 39.142 --xmin -84.313 --xmax -84.163857
  File "C:\Users\Chaska\Desktop\TopoMC\TopoMC\GetDataset.py", line 120
    print "no attributes found"
                              ^
SyntaxError: invalid syntax

i am running windows 7x64

**Comment by mathuin** [comment]
I ran your command on my system and successfully retrieved the region.  Could you run your command again with --debug enabled, and post the resulting output?  It will help me narrow down the problem.

GetDataset.py --debug --region Milford --ymax 39.230 --ymin 39.142 --xmin -84.313 --xmax -84.163857

Also, I'm excited that you run Windows.  I'm hoping you will be able to confirm that the file access code will work on your system. :-)

Jack.

**Comment by thehighpander** [comment]
C:\Users\Chaska\Desktop\TopoMC\TopoMC>GetDataset.py --debug --region Milford --y
max 39.230 --ymin 39.142 --xmin -84.313 --xmax -84.163857
  File "C:\Users\Chaska\Desktop\TopoMC\TopoMC\GetDataset.py", line 120
    print "no attributes found"

**Comment by mathuin** [comment]
When was the last time you updated your checkout?  When I run that command, I get a large amount of debug output, including a bunch of XML from the USGS web services which helps me diagnose problems like that.  Could you update your checkout and try again?

Jack.

**Comment by mathuin** [comment]
I am closing the issue until I hear from you regarding the updated checkout.  Thanks!

Jack.
