### ISSUE TITLE
How to generate larger scaled worlds?

### ISSUE THREAD

**Issue by AceofCrafters** [mathuin/TopoMC#23]
Let me start by saying that I just setup your software today for windows and all is well. I was able to generate 2 worlds, one with custom coordinates, and I am extremely satisfied with the results. However, I would like the size to be more realistic. I generated (python ./GetRegion.py --name PurcellLake --ymax 34.99837 --xmin -97.406287 --ymin 34.971437 --xmax -97.367234) a lake I visit often near my hometown. My server that I host has stacked worlds using the mineup mod. This works by extending the height 5X  using 5 regular worlds stacked atop one another. I have my worlds setup as follows: bottom world is underground filled with caves and ores which I custom generate, second layer is like a regular minecraft map in some places, in other places the height of the ground rises to the next level above. The third layer is the same as the second, but keep in mind they all connect and as you go up you switch to the higher world maps. Hills & Mountains start on any layer with ground and can extend up to the top of the fifth layer.Can you please make it possible for the program to do this: 3X3 blocks wide 1 block tall for every block in the current 1:1 scale. It should fit in the 256 height limit of the map:the amount of blocks from lake bed to highest point is 37 in the default scale 1:6 in 1:1 that would be 222 blocks tall. It should fit without ores. I can use mcedit to place it in the appropriot layer and smooth it out. Reseblance problems can be fixed in this project so I don't  care if it looks choppy, that can be fixed with world painter and mcedit. By the way this project and Dwarf Fortress to Minecraft by TroZ https://github.com/TroZ/DF2MC are my favorite minecraft generators so far; keep up the great work.
Thanks,
               Ace

**Comment by mathuin** [comment]
This is an interesting idea.  Unfortunately, the assumption of 1:1 being the smallest scale is embedded throughout the code.  You could get a similar effect by creating a map with --scale 1 --vscale 3 of a lake that's three times the size of Purcell Lake.  Lake Thunderbird looks on the map to be about 12-15 times the size of Purcell Lake, so you could try --scale 6 --vscale 18 or --scale 10 --vscale 30 and see if it's close enough for your purposes.  Does that help?

Jack.

**Comment by AceofCrafters** [comment]
Great, Ill try it when I get home, and thanks for the quick reply even on thanksgiving day.

**Comment by AceofCrafters** [comment]
The output of Lake Thunderbird looks really good on my map for the moment. I am searching for a program to convert every block in minecraft to a custom ammount of blocks. Ill make a suggestion on the mc forums. I think other people would like a map converter like that as well. If I find one ill post the link here.

**Comment by mathuin** [comment]
It's been a few months and there hasn't been any action on this issue so I'm going to close it.
