### ISSUE TITLE
Getting AttributeError when running BuildRegion.py

### ISSUE THREAD

**Issue by freeradicalx** [mathuin/TopoMC#27]
Well first of all I've never gotten this far in attempting to create a TopoMC map, so it looks like the new hotfix is working for me (Many thanks and great work!). This error, as far as I can tell, is unrelated to the recent fix. I'm in OS X 10.7.5.

I'm running your commands from the 3rd, 4th and 5th steps in the readme to test. I get as far as running BuildRegion.py but after a minute or so of processing (With all 8 cores, nice) I get the following:

Traceback (most recent call last):
  File "./BuildRegion.py", line 119, in <module>
    main()
  File "./BuildRegion.py", line 75, in main
    pool.map(buildtile, tiles)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 199, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 491, in get
    raise self._value
AttributeError: 'AnvilChunk' object has no attribute 'compressedSize'

And I assume this is an mcedit thing, but I really have no idea. Any guidance?

**Comment by mathuin** [comment]
Well, it's a pymclevel thing I think, but it could be related to a number of issues.

Could you post your ./GetRegion.py command line with all arguments so I can attempt to recreate the problem locally?

Jack.

_ETA:_ If you are doing the exact ./GetRegion.py found in the README.pm, that's fine, I didn't see that on my first read-through.  If you've changed anything at all like scale or coordinates or depth, let me know!

**Comment by mathuin** [comment]
Okay, I ran those three commands and "it worked for me".  I'm going to move aside my existing checkout and start from scratch with all five commands to see what happens.

**Comment by mathuin** [comment]
Yep, did it all from scratch and couldn't reproduce the problem.

If you could try moving aside your current checkout and cloning the software again, then running all five commands and cutting-and-pasting the output, I'd really appreciate it!

Jack.

**Comment by freeradicalx** [comment]
Will do, may not have that for you until the evening since I'm about to run out to work (I don't get a spring break :( ), but in the meantime I should mention I may have the mcedit files installed incorrectly. I basically just put all the files from https://github.com/mcedit/pymclevel into the empty /TopoMC/pymclevel folder, and I'm wondering if that's not the way to go about things.

Edit - Just took a good look at steps 1 and 2 in the readme which I had passed up before as being ubuntu-specific. I now see that they're dealing directly with pymclevel, d'oh. I'll make sure I run all 5 commands this time :P

**Comment by freeradicalx** [comment]
Yup, that's the problem. Step 2's got me stumped. I'm new to this Git thing and am learning so I'm probably just missing something obvious. Step 1 runs fine as far as I can tell:

Nathans-Hackintosh:TopoMC nathan$ git submodule init
Submodule 'pymclevel' (git://github.com/mcedit/pymclevel.git) registered for path 'pymclevel'

But then Step 2, if I type the command as you have it in the readme gets me:

Nathans-Hackintosh:TopoMC nathan$ (cd pymclevel && python setup_nbt.py build)
python: can't open file 'setup_nbt.py': [Errno 2] No such file or directory

Now, I don't know if I should have entered your command as you have it in the readme (In parenthesis like that), but there's nothing in the pymclevel folder after cloning in TopoMC, so the command python steup_nbt.py build doesn't work. Even if I clone https://github.com/mcedit/pymclevel to the pymclevel folder it doesn't come with that file.

So I think I'm just installing it wrong. What am I missing?

**Comment by mathuin** [comment]
Ah, the docs are not formatted correctly!

After you clone the TopoMC checkout, run this command (like you did): git submodule init

Then run this command:  git submodule update

They are two separate commands!  However, the README doesn't show that. :-(

You can then run the command in parentheses once the update is complete.  That parenthetical command steps into the pymclevel directory temporarily and runs the setup_nbt.py build command to build the accelerated NBT code.

Sorry about that problem with the git commands.  I will fix the README!

Jack.

**Comment by mathuin** [comment]
1.  Import the pymclevel submodule.  Must be done once before anything else!  There are two commands here, init and update:
   
   ```
   jmt@belle:~/git/TopoMC$ git submodule init
   jmt@belle:~/git/TopoMC$ git submodule update
   ```
2.  (Optional) Compile the accelerated NBT module in pymclevel.
   
   ```
   jmt@belle:~/git/TopoMC$ (cd pymclevel && python setup_nbt.py build)
   ```
3.  Retrieve the region from the USGS.
   
   ```
   jmt@belle:~/git/TopoMC$ ./GetRegion.py --name Provincetown --ymax 42.0901 --xmin -70.2611 --ymin 42.0091 --xmax -70.1100
   ```
4.  Prepare the region for processing.
   
   ```
   jmt@belle:~/git/TopoMC$ ./PrepRegion.py --name Provincetown
   ```
5.  Construct the Minecraft world based on the region.
   
   ```
   jmt@belle:~/git/TopoMC$ ./BuildRegion.py --name Provincetown
   ```

**Comment by freeradicalx** [comment]
It works! Screenshared with my machine at home and gave it a try, PrepRegion took about 14 minutes and BuildRegion took about 42 minutes to finish off the Provincetown example, leaving me with Worlds/Provincetown/region full of small .mca files, and small level.dat file in Worlds/Provincetown. /Maps is still empty but I assume that's normal seeing as BuildRegion completed without errors. Thanks so much for the help! I'm gonna have fun with this tonight :)

**Comment by mathuin** [comment]
There's one more tool included -- ./BuildMaps.py -- that will generate a single image of the entire map, or a GoogleMaps-esque zoom and browse sort of thing, depending on the command line arguments.  It requires that c10t be installed, which is why I don't mention it by default.  That's how I generated the images on the showcase.

I am glad it worked.  I apologize again for the confusion. :-)

Jack.

**Comment by freeradicalx** [comment]
Hey no problem! This is homebrew software and honestly getting it to run on my OS was half the fun. Once I get better at it and play around with it a little more I might put together an installation tutorial for OS X, tracking down dependencies on the Mac is about 100 times harder than doing the same thing in Linux, especially when you don't know the first thing about compiling from source and need a premade binary, so now that I've gotten this far I'd like to bridge that gap for others.

**Comment by mathuin** [comment]
Let me know when you get a rough draft of that doc, we can set up a wiki page like the one for Windows.  All three other potential Mac OS X users will appreciate your efforts. ;-)  Seriously, it's people that like you that help me help everyone else who uses your gear.  Thank you. :-)

Jack.

**Comment by KermMartian** [comment]
Thanks for this "bug" report; I had exactly this problem and the git submodule init\update did the trick for me. I had initially just pointed a symlink at my previously-installed pymclevel directory.
