### ISSUE TITLE
No module named progressbar

### ISSUE THREAD

**Issue by bidwbb** [mathuin/TopoMC#28]
Apologies in advance for my technical naivety...

I had TopoMC installed and I think working before (though it was after USGS changed things so never successfully run).
This morning:

> git pull git://github.com/mathuin/TopoMC.git inside of TopoMC/TopoMC
> git submodule init
> git submodule update

then

> ./GetRegion.py --name Provincetown --ymax 42.0901 --xmin -70.2611 --ymin 42.0091 --xmax -70.1100
> Traceback (most recent call last):
>   File "./GetRegion.py", line 5, in <module>
>     from region import Region
>   File "/Applications/TopoMC/TopoMC/region.py", line 10, in <module>
>     from progressbar import ProgressBar, Percentage, Bar, ETA, FileTransferSpeed
> ImportError: No module named progressbar

**Comment by freeradicalx** [comment]
Heh, ran into this myself last night. progressbar is a Python library you have to install separately, I don't think it was required before but with the recent update Jack added download progress text to the GetRegion script, which utilizes the progressbar library. Download it from here: http://code.google.com/p/python-progressbar/downloads/list

Once you unpack it, cd to the extracted directory and run sudo ./setup.py install to install it into python.

**Comment by mathuin** [comment]
What @freeradicalx said.  It's new since the downloads are so huge, and I will probably use it in the region building code which has no sense of progress.  I will update the documentation to reflect the new requirement.

Thanks!

Jack.

**Comment by mathuin** [comment]
Oh, one last thing:  if you don't use Ubuntu to track things, you can also install the module with pip or easy_install:

```
pip install progressbar
```

One of these days, if GDAL ever expands the warp API to Python, this will be a pure Python package and I can use virtualenv and friends.  That'll be the day. :-)

**Comment by abobakrosman** [comment]
> 
> 
> Oh, one last thing: if you don't use Ubuntu to track things, you can also install the module with pip or easy_install:
> 
> ```
> pip install progressbar
> ```
> 
> One of these days, if GDAL ever expands the warp API to Python, this will be a pure Python package and I can use virtualenv and friends. That'll be the day. :-)

I had install progressbar  using pip install progressbar , but still the same error  
from progressbar import Bar
ModuleNotFoundError: No module named 'progressbar'

**Comment by mathuin** [comment]
It's been over five years since this issue was closed, so I thought I'd check to see if progressbar still exists.  It's still on PyPi, and I can still install it with `pip install progressbar`, and `from progressbar import Bar` works for me.  I think you should start by double-checking that your virtualenv is activated, and that you successfully installed the module.  After that, I'm not sure.  Are you using TopoMC, or did you find this issue through a web search?  I'm curious!  Good luck!

**Comment by abobakrosman** [comment]
-Iam using normal cmd but its only work after install progressbar using 
**python3.6 -m pip install progressbar**

**Comment by mathuin** [comment]
Interesting!  I've never done it that way before.  I think what it's doing is creating what amounts to a per-user virtualenv, storing the module in a cache in the home directory.  Thank you for the update!

**Comment by Gabit07** [comment]
> > Oh, one last thing: if you don't use Ubuntu to track things, you can also install the module with pip or easy_install:
> > ```
> > pip install progressbar
> > ```
> > One of these days, if GDAL ever expands the warp API to Python, this will be a pure Python package and I can use virtualenv and friends. That'll be the day. :-)
> 
> I had install progressbar using pip install progressbar , but still the same error
> from progressbar import Bar
> ModuleNotFoundError: No module named 'progressbar'

Did you solve the problem?

**Comment by mathuin** [comment]
progressbar can be installed successfully with pip nowadays on Python 2.7, as is seen below.

```
jmt@belle:~$ source tweet/bin/activate
(tweet) jmt@belle:~$ pip install progressbar
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting progressbar
Installing collected packages: progressbar
Successfully installed progressbar-2.5
(tweet) jmt@belle:~$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from progressbar import Bar
>>> 
```

**Comment by Gabit07** [comment]
> progressbar can be installed successfully with pip nowadays on Python 2.7, as is seen below.
> 
> ```
> jmt@belle:~$ source tweet/bin/activate
> (tweet) jmt@belle:~$ pip install progressbar
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> Collecting progressbar
> Installing collected packages: progressbar
> Successfully installed progressbar-2.5
> (tweet) jmt@belle:~$ python
> Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
> [GCC 7.3.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from progressbar import Bar
> >>> 
> ```

I know! I can import in the terminal like you. But in the jupyter notebook I am having problem to import 

if I enter this in a cell and run it, it outputs this
Requirement already satisfied: progressbar in /usr/local/lib/python3.5/dist-packages (2.5)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-007c3af5f6ab> in <module>()
      1 get_ipython().system(u'pip install progressbar')
----> 2 from progressbar import ProgressBar

ImportError: No module named progressbar

**Comment by mathuin** [comment]
Huh!  No idea.  I think you should consider filing an issue here: https://github.com/jupyter/notebook/issues

**Comment by Gabit07** [comment]
> Huh! No idea. I think you should consider filing an issue here: https://github.com/jupyter/notebook/issues

Yeah, I've just created an issue there

**Comment by asmajavaidd** [comment]
hi I am trying to run my this below code but it is showing error as ModuleNotFoundError: No module named 'progressbar'. I already installed this command pip install progressbar from command line. 
Between I am running the code on spyder.

import warnings
import pandas as pd
from progressbar import ProgressBar
import math
pbar = ProgressBar()
warnings.filterwarnings("ignore")


df = pd.read_csv("data/downloaded_data.csv", dtype='unicode')

print("Length of dataframe before cleaning: {}".format(len(df)))

# Trimming the columns
df = df[['Respondent','YearsCodingProf','YearsCoding','Employment','FormalEducation', 'Country', "OpenSource", 'JobSatisfaction',
'UndergradMajor','DevType','Currency' ,'Salary' ,'ConvertedSalary' ,'CurrencySymbol' ,'Sala

**Comment by mathuin** [comment]
I'm sorry, you've found the wrong repository.
