### ISSUE TITLE
Can't use --sealevel or --maxdepth

### ISSUE THREAD

**Issue by mrklaw** [mathuin/TopoMC#3]
When I try to use the --sealevel or --maxdepth options with BuildArray.py I get the following error not matter what I specify:

BuildArrays.py: error: argument --sealevel: invalid checkSealevel value: '10'

where 10 is the value I specify.

I've looked through the checkSealevel function but my python is a bit rusty. Is it possibly a type error? I have the exact same problem if I try to use --maxdepth

I've tried in both the main and develop branches

**Comment by mathuin** [comment]
A quick workaround until I fix this:  you can change default_sealevel and default_maxdepth in BuildArray.py and then rerun the script to get the desired values.

Thank you for reporting this issue!

**Comment by mrklaw** [comment]
Exactly what I did, though I'm not sure that it worked.  The area I'm trying to map is starting at block 80  or so, which is I think why it's forcing me into a vscale of 8 or more.  I keep ending up with these giant rectangular flat plateaus.  The area I'm trying to map is here: --ymin 35.596426 --ymax 35.616314 --xmin -82.459860 --xmax -82.418232 .  A pretty mountainous region, which is why I was trying to lower sealevel.  Maybe I'm going about it incorrectly though.

Thanks for the quick reply!

**Comment by mathuin** [comment]
Ah, I broke stuff when moving it to argparse.  My fault.  I should have a fix out sometime tonight.  Thanks!

**Comment by mathuin** [comment]
Yes, I'm seeing the vertical scale defaulting to 10 because 6 is too small.  I don't know if you'll have enough room even if you lower the sealevel and shrink the maxdepth.

I really really wish Minecraft would break through the 128 block height limit soon.  Supposedly 1.0 will have that feature, but I haven't seen it.  When pymclevel supports a larger height, I will be very excited to give it a try, trust me!

**Comment by mrklaw** [comment]
That would be really nice!  I would still think I should be able to get something a little better than I'm getting.  Here is the map I get with default_sealevel changed to 10 and default_maxdepth changed to 5.  I set scale to 5 as well.

http://www.warren-wilson.edu/~sloan.poe/vscale.png

I'm wondering about the rift in the middle as well as the odd sunken depression in the lower left corner.  And except for the left corner the lowest point in the map is level 86.

**Comment by mathuin** [comment]
You have to delete the contents of the Worlds/mrklaw directory (or whatever you named that world) before rerunning ./BuildWorld.py --region mrklaw.  You can tell because the little area is the same as the big area just shrunk.

The fix I am working on for issue #3 will include this pre-build cleanup.

**Comment by mrklaw** [comment]
Oops.  I feel a little dumb for missing that.   I had been trying to use different region names each time I ran it.  I guess I got a little sloppy.  I still don't understand what's going on with the extreme drop off in the corner however.  I think that's my main elevation problem.  Is there a way for me to see the raw elevation data from USGS?  

Also is there a better place for me to ask you these questions?  I don't want to keep cluttering this issue since it seems a little more straight forward than my personal mapping issues.

**Comment by mathuin** [comment]
You can send me email at mathuin@gmail.com for the stuff unrelated to issue #3.  As for the dropoff, I suspect it's related to the data you're using.  You can confirm that by rerunning ./GetDataset.py with the additional parameter --elevationIDs NED or --elevationIDs ND3.  You'll have to do that from the develop branch, though.

**Comment by mathuin** [comment]
Okay, I just realized that fixing the maxdepth/sealevel problem the right way is going to involve rewriting the array and world stuff as classes, and that's going to take more time than I have tonight.  I will work on it over my trip.

I will commit a fix to the world-deleting problem you mentioned earlier to the develop branch, and will keep this issue open until the proper solution has been implemented.

**Comment by mathuin** [comment]
The world-deleting problem has been fixed in the develop branch.

**Comment by mathuin** [comment]
There has been some progress on your request. :-)

I have been rewriting TopoMC to use a different organizational structure.  The git branch is "feature/regions".  The new version has proper sealevel support, but maxdepth won't be fully supported until I port the bathy feature to the new system which I am hoping to do this week.  There are a lot of other improvements as well, including a resolution to the "dropoff" issue you mention above.  When I merge the new feature, I will update this issue and close it.  Thank you for your patience!

**Comment by mrklaw** [comment]
Awesome and funny.  I just started thinking about messing with this again today.  Is the features/regions branch in a state where I could do some testing?

**Comment by mathuin** [comment]
Mostly.  The terrain is very blocky and simple right now -- dirt or water -- and my goal for today is to finish the redesign of the terrain module to handle multiple types of landcover files.  Fixing the blockiness (more obvious at low scale values) is harder.  Anyway, after I finish the terrain design, I need to redo trees and ore and buildings and I'll be done with the new feature!

Just 'git pull; git branch feature/regions' and you should have functional code.  I try not to push until stuff works!

Here is how to build Block Island with the new code:

./GetRegion.py --name BlockIsland --ymax 41.2378 --ymin 41.1415 --xmin -71.6202 --xmax -71.5332 --scale 6 --vscale 6 --trim 0 --sealevel 64 --maxdepth 32
./BuildRegion.py --name BlockIsland

The last five arguments of the ./GetRegion.py line show the default values for those parameters.  There's still some extra output which is helping me refine the vscale/trim code, but it can be ignored.

Give it a try and let me know what you think!

**Comment by mathuin** [comment]
I have merged the regions feature (with working sealevel/maxdepth code) into develop, so I'm closing this ticket.  

Thank you again for submitting the issue, and let me know how the develop branch works for you!

Jack.
