### ISSUE TITLE
Warning 6: gdalbuildvrt does not support heterogenous projection. Skipping [path+filename].tif

### ISSUE THREAD

**Issue by directgumby** [mathuin/TopoMC#33]
Hello,

I am creating a map based on an island in the Flathead Lake region in MT using --ymax 47.8610 --xmax -114.2506 --ymin 47.8287 --xmin -144.1782

In doing this I got an error saying "gdalbuildvrt does not support heterogenous projection."  

I am not sure if this will be an issue or not for the TopoMC but I thought I should check and see if: 1) is this an issue and 2) will this cause problems with the map?

Thanks,
Brett

**Comment by mathuin** [comment]
The difference between your xmax and xmin is thirty degrees -- I tried your commands with -114.1782 for the xmin and the region looks normal.  Can you double check your parameters?

**Comment by directgumby** [comment]
Hello Jack,

Good catch - I was wondering why it was downloading so many grid segments.

After bringing this chord back into reality, all looks much better!

Thank you for your time and help.

Brett

Sent from Windows Mail

From: Jack Twilley
Sent: ‎Sunday‎, ‎August‎ ‎18‎, ‎2013 ‎6‎:‎08‎ ‎PM
To: mathuin/TopoMC
Cc: directgumby

The difference between your xmax and xmin is thirty degrees -- I tried your commands with -114.1782 for the xmin and the region looks normal. Can you double check your parameters?
