### ISSUE TITLE
Observastions on my attempt to create a map 

### ISSUE THREAD

**Issue by directgumby** [mathuin/TopoMC#35]
Hello,

I have been working to build a map of the Flathead region.. In doing this I have run into a few issues around memory and the time to do the "prepregion."

Setup: Xeon dual core server, 8gigs of RAM, Swap file increased to 40Gigs to start 50Gigs max.

Area: 
getregion.py --name Flathead --ymin 47.6765 --ymax 48.2211 --xmin -114.0096 --xmax -114.4545 --vscale 14 --enable-schematics

Other: I compiled the NBT code to help performance and this is running on a Window 2012 sever setup.

Some interesting stats:
The "high level" committed memory on the swap file grew to 41.2 gigs and it is still processing at over 12 hours to create.

I am not sure if others have run into this type of issue or if there is something odd about this region.  

I am not sure how well this will all come together, but I'll let folks know.

Thanks,
Brett

**Comment by mathuin** [comment]
The single thing you can do to improve performance during prepregion.py is to get the OpenCL stuff working.

If your video card can play Minecraft, odds are it can run OpenCL.  It is particularly well suited to the sorts of math that prepregion.py uses to prepare the region for construction.  Lots less RAM required, lots faster.

**Comment by directgumby** [comment]
I will give that a try next time around!
Thank you for your time and help.

This is a very cool and I really appreciate all of your help.

Thanks,
Brett
