### ISSUE TITLE
pyOpenCL error - any thoughts?

### ISSUE THREAD

**Issue by directgumby** [mathuin/TopoMC#36]
Hello,

I have installed pyOpenCL and after doing so I end up with this issue:

  File "C:\Python27\lib\site-packages\pyopencl__init__.py", line 28, in <module>
    import pyopencl._cl as _cl
AttributeError: 'module' object has no attribute '_cl'
C:\Users\Brett\Documents\GitHub\TopoMC [develop]> import pyopencl._cl as _cl

When I run the basic test:
C:\Users\Brett\Documents\GitHub\TopoMC [develop]> python .\GetRegion.py --name Provincetown --ymax 42.0901 --xmin -70.2611 --ymin 42.0091 --xmax -70.1100 --debug

Do you have any thoughts on how I may solve this?
I'd like to put the OpenGL card to work if possible.

Thanks,
Brett

**Comment by mathuin** [comment]
It sounds as if there are a few missing pre-requisites.  Were you able to install OpenCL on your Windows system?  Which video card do you have?

Jack.

**Comment by directgumby** [comment]
Hey Jack,

I have an Intel hd graphics 2000 on this system.  I installed the driver with the open gl icd, I installed pyopencl from the same location as pyyaml and such for windows.

I'll recheck all of my packages.

Thanks,
Brett

Sent from my Windows Phone

**Comment by mathuin** [comment]
http://clbenchmark.com/benchmarks.jsp?benchmark=download

If you can run this benchmark successfully, then your card is set up for OpenCL.  If you could post the results, that would be helpful!  The "Programming Principles" category is most like what TopoMC does.  

Jack.

**Comment by directgumby** [comment]
Hello Jack,

After looking at this part: 
"Intel® HD Graphics supports OpenCL\* only on the 3rd Generation Intel® Core™ Processors with the Intel® HD Graphics 4000/2500."

I see now why on this system it is not working.
It is a gen2 2000 HD graphics card.

Thank you for the pointer - that really helped me figure out what is going on there.

Thanks,
Brett

Date: Sun, 25 Aug 2013 17:18:55 -0700

**Comment by directgumby** [comment]
I think that Intel's initial support is rather weak it seems... I've tried another system with a Intel HD 4000 and after doing more reading I need to delete some files from the system to get the OpenCLBench to run properly and so on... I am not going to continue to peruse this at this time - hopefully OpenCL and Intel will get this working smoothly in the future.

Thank you for your help on this.
Brett
