### ISSUE TITLE
Question on tilesize: Why would I change this?

### ISSUE THREAD

**Issue by directgumby** [mathuin/TopoMC#37]
Hello,

I think I understand the rest of the switches for TopoMC but it is not clear to me why I would change the tile size?

Can you help me understand what this will do when creating a map?

Thanks,
Brett

**Comment by mathuin** [comment]
A smaller tilesize reduces the size of individual jobs which can help with some memory issues.  A larger tilesize reduces the number of individual jobs which can help with some speed issues.  I tend to leave it where it is, to be honest. :-)

Jack.

**Comment by directgumby** [comment]
Great info, I'll give tis a try to see if it lowers my overall resources as right now I have a HUGE swap file setup (literally 400 Gigs!) to process a small section of the Flathead lake (even with that full amount I cannot process it without running out of memory - crazy stuff).
