### ISSUE TITLE
Water (still) in terrain.py should be simply Water

### ISSUE THREAD

**Issue by mrklaw** [mathuin/TopoMC#4]
In the most recent version pymclevel "Water (still)" has been changed to "Water"

**Comment by mathuin** [comment]
The pymclevel materials changes will be the death of me, I swear. :-)

If you know of any other changes in pymclevel that may affect TopoMC, please mention them in this issue and I'll try to hit them over the Thanksgiving break.  For now, as you have almost definitely figured out, you can get around that by changing the appropriate text values in terrain.py.  And ugh, I should consider refactoring that, too.

Thank you for reporting the issue!

**Comment by mathuin** [comment]
In addition to "Water (still)" changing to "Water", "Lava (still)" has changed to "Lava".  All the rest look the same as far as I can tell.

I have committed a fix to this issue to the develop branch.

By the way:  there are a few new items, such as tall grass, that'd be nice to support in the future.  I will keep this in mind for a later update.
