### ISSUE TITLE
Failure in GetDataset.py

### ISSUE THREAD

**Issue by ylluminate** [mathuin/TopoMC#5]
On Ubuntu I managed to install apparently all of the deps for GetDataset.py, however when I finally get the script to run without dependency problems, I run into the following issue and would appreciate any input as to what may be the error here:

Retrieving new dataset MyRegion...
Checking inventory service for coverage.
Traceback (most recent call last):
  File "./GetDataset.py", line 472, in <module>
    sys.exit(main(sys.argv))
  File "./GetDataset.py", line 443, in main
    productIDs = checkInventory(args)
  File "./GetDataset.py", line 98, in checkInventory
    lcProduct = checkAvail(args.xmin, args.xmax, args.ymin, args.ymax, landcoverIDs)
  File "./GetDataset.py", line 131, in checkAvail
    for elem in rAatts.ArrayOfCustomAttributes:
AttributeError: 'Text' object has no attribute 'ArrayOfCustomAttributes'

**Comment by ylluminate** [comment]
Managed to produce the same error on Mac OS X by using brew for python and gdal (`brew install gdal --use-gcc`) as well as using pip to install suds, lxml, numpy (requirement for brew's gdal) and gdal.

The command I'm running is: `./GetDataset.py --region MyRegion --ymax value --ymin value --xmin value --xmax value`

**Comment by ylluminate** [comment]
By the way, just want to thank you @mathuin so very much for your efforts on this.  What a wonderful tool as it has some very practical applications!

**Comment by mathuin** [comment]
I am glad you like TopoMC!  I have found it to be useful for visualization as well as fun to create an imaginary world based on real life.

Could you give me the exact values for the arguments?  I would like to run them myself.  I am 99% certain that an error is being returned instead of useful data, and that I have to either check the arguments first or catch an unexpected result.  Either way, I would like to test to make sure that my fix works for you.  Thanks!

Jack.

**Comment by ylluminate** [comment]
Yes indeed, I actually have wanted to build some test structures for real life to explore distance and relationships, and I think this will be amazing.

I've changed the offsets here as I can't provide the real value's for a few reasons, but they produce the same result.  If I use the same values truncated to hundredths it still replies with the same error:
./GetDataset.py --region TestTown --ymax 49.02777777777778 --ymin 48.99861111111111 --xmin 92.67277777777778 --xmax 92.71944444444445

I was not able to get the actual decimal values from Google Maps and ended up having to convert the degrees to decimal, so I am curious if perhaps that is source of the error now that you mention that.

**Comment by mathuin** [comment]
When I ask Google Maps to take me to 49.02N,92.67W it takes me to Canada.

Alas, TopoMC only works on the United States.  Support can be added for Canada if they offer the right kind of data via web service, otherwise you'll have to retrieve and transform it by hand before ./BuildArray.py can work with it.

Are you sure you have the right location?

Jack.

**Comment by ylluminate** [comment]
Well, i'm sorry, the actual data is well below that.  It's off by about 10 degrees.  Tell you what, first, give me the precise URL you're using to pull this up with Google Maps as I'm not finding the function you described in the readme initially.  It appears that you're seeing this in another way than what was described (and I do recall from the past being able to easily look up lat/long, however I'm not seeing it now).  Ultimately I pulled up a fence on: http://edcsns17.cr.usgs.gov/NewEarthExplorer/ -- Google Earth also worked, but again, both of these were in degrees / minutes / seconds vs decimal notation.

**Comment by mathuin** [comment]
All I did was open Google Maps and type in "49.02N,92.67W".  That simple. :-)  The URL is: http://maps.google.com/maps?q=49.02N,92.67W&hl=en&sspn=0.010818,0.02238&vpsrc=0&t=m&z=14 which gives me a point in Ontario.  There is a tiny link "Maps Labs" on the left side which if selected will allow you to enable a latlong tooltip as well as the ability to place a latlong marker.  I use the markers to select the upper-left and lower-right corners of a space which I can then use with ./GetDataset.py to retrieve the relevant data.

I recognize that your exact precise coordinates are privileged, but if you can give me rough estimates or somewhere nearby, that'll be fine -- as long as it's in the United States and generates the same error message, I can fix the bug if there is one.

Jack.

**Comment by mathuin** [comment]
One last idea without knowing the new coordinates:  be sure to use _negative_ values for the X coordinates.  They are west of Greenwich which is a negative value in this coordinate system.  I mention this in the documentation but even I sometimes forget. :-)

Jack.

**Comment by ylluminate** [comment]
:) LOL, sorry, I wasn't referring to how you searched for the coordinates, but rather how you obtain lat/long from google maps initially (ie, picking out the upper left and lower right points on the rectangle as you refer to it in the readme).  Yes, the second is to what I was referring.  It's accessed through the google gear in the upper left and then going to labs, yes: http://j.mp/sP9FAN

Wow!  But yes indeed, I had failed to think of the negative x coords.  That has done the trick, thanks very much.  Now I'll move along here to see how it proceeds!!!

**Comment by ylluminate** [comment]
By the way, it might be a good idea to specify negating x coords, unless I missed that somewhere (looked again did not see it at a glance).  In the instructions you might add a shell comment: "#negate x coordinates for U.S." after the command.

**Comment by mathuin** [comment]
I do mention it in the --help for ./GetDataset.py but I will add it to the README after the sample command for Block Island.  Thanks for the pointer, and I'm glad you were able to get it to work!

Jack.

**Comment by ylluminate** [comment]
Well, I'll continue on here for the moment unless you'd like for me to create a new ticket.  Presently I moved along to BuildArrays.py and received an error:
`./BuildArrays.py --region TestTown`

Traceback (most recent call last):
  File "./BuildArrays.py", line 13, in <module>
    from tile import checkTile, checkStartEnd, processTiles
  File "/Users/username/bin/mc/TopoMC/tile.py", line 2, in <module>
    import Image
ImportError: No module named Image
--END ERROR--

I'm assuming that I'm missing another module, but this one is not readily making itself visible from exploring modules with pip or easy_install.

**Comment by mathuin** [comment]
The Image module is part of PIL, the Python Imaging Library.  I think it was installed on my system already, but you'll want to apt-get python-imaging to install it on your system.  More documentation updates!

Jack.

**Comment by ylluminate** [comment]
Running on Mac OS X, so I have to establish a few dependencies:
brew install python #if you want to use the non-system default python
/usr/local/share/python/pip install numpy
brew install gdal --use-gcc
/usr/local/share/python/pip install suds lxml

/usr/local/share/python/pip install pil
brew install gfortran
/usr/local/share/python/pip install scipy

## 

However now I'm on to pymclevel and not finding that one again.

**Comment by mathuin** [comment]
pymclevel is found on github, which is mentioned in the README but without an actual command line to grab it.  The Minecraft Wiki has a TopoMC page I've been using for online documentation, I think it's mentioned there.

Jack.

**Comment by ylluminate** [comment]
Well, it was essentially a matter of cloning it down and then mv'ing or cp'ing it over to the TopoMC folder (at least that's what I intuitively did).  Now I'm seeing another seeming error, but the script is processing the region presently.
Here's the output / error I'm seeing just before the script telling me that it's processing the region:
Import error loading precompiled _nbt extension. Trying pyximport...
Import error loading _nbt extension ImportError('No module named pyximport',)
Traceback (most recent call last):
  File "/Users/username/bin/mc/TopoMC/pymclevel/nbt.py", line 8, in <module>
    from pyximport import install; install()
ImportError: No module named pyximport
--END ERROR--

Perhaps that's not important?  We shall see...

Hmm, seeing a lot of these:
...
WARNING:mcarray:unknown block value: Stone
WARNING:mcarray:unknown block value: Bedrock
WARNING:mcarray:unknown block value: Dirt
WARNING:mcarray:unknown block value: Stone
WARNING:mcarray:unknown block value: Grass
...

**Comment by mathuin** [comment]
You don't want pymclevel _in_ the TopoMC directory.  You want the pymclevel clone to be in the same directory as the TopoMC clone.  On my system, they are ~/git/pymclevel and ~/git/TopoMC respectively.  This is mentioned on that wiki page.

The unknown block values are a sign that you're doing something crazy. :-)

Jack.

**Comment by ylluminate** [comment]
Right, pymclevel was checked out in the parent folder then I mv'd it on over into TopoMC.  

Hmmm.  It's still pouring through the WARNING messages ad infinitum.  Seems as though something is indeed wrong.  Perhaps the `ImportError: No module named pyximport` line?

That did finally finish:
...
WARNING:mcarray:unknown block value: Stone Stairs
WARNING:mcarray:unknown block value: Stone Stairs
WARNING:mcarray:unknown block value: Stone Stairs
WARNING:mcarray:unknown block value: Stone Stairs
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
WARNING:mcarray:unknown block value: Torch
Consider setting spawn point to 512, 48, 595
Land cover statistics (462344 total):
  215909 (46.70%): Deciduous Forest
  122929 (26.59%): Pasture/Hay
  33561 (7.26%): Evergreen Forest
  28207 (6.10%): Grasslands/Herbaceous
  25121 (5.43%): Developed/Open-Space
  13743 (2.97%): Developed/Low-Intensity
  10496 (2.27%): Cultivated Crops
  4483 (0.97%): Developed/Medium-Intensity
  4431 (0.96%): Water
  3326 (0.72%): Shrub/Scrub
  138 (0.03%): Mixed Forest
Tree statistics (7180 total):
  6198 (86.32%): Redwood
  951 (13.25%): Birch
  26 (0.36%): Regular
  5 (0.07%): Shrub
Ore statistics (0 total nodes, 0 total veins):

**Comment by mathuin** [comment]
Looks like pymclevel has changed again in the past two weeks.  Sigh. :-)

I will take a closer look at this later today.  By the way, no need to move pymclevel, just leave it in the parent folder.

Jack.

**Comment by ylluminate** [comment]
However even though that finished, the next step yielded failure:
`./BuildWorld.py --region TestTown`

Import error loading precompiled _nbt extension. Trying pyximport...
Import error loading _nbt extension ImportError('No module named pyximport',)
Traceback (most recent call last):
(same error as before)
Creating world from region TestTown
Traceback (most recent call last):
  File "./BuildWorld.py", line 46, in <module>
  File "./BuildWorld.py", line 40, in main
  File "/Users/username/bin/mc/TopoMC/mcarray.py", line 161, in loadArrays
  File "/Users/username/bin/mc/TopoMC/mcarray.py", line 147, in loadArray
  File "/Users/username/bin/mc/TopoMC/pymclevel/infiniteworld.py", line 2861, in createChunk
  File "/Users/username/bin/mc/TopoMC/pymclevel/infiniteworld.py", line 635, in __init__
  File "/Users/username/bin/mc/TopoMC/pymclevel/infiniteworld.py", line 805, in create
  File "/Users/username/bin/mc/TopoMC/pymclevel/infiniteworld.py", line 813, in save
  File "/Users/username/bin/mc/TopoMC/pymclevel/infiniteworld.py", line 2602, in _saveChunk
  File "/Users/username/bin/mc/TopoMC/pymclevel/infiniteworld.py", line 1270, in saveChunk
  File "/Users/username/bin/mc/TopoMC/pymclevel/infiniteworld.py", line 1326, in _saveChunk
  File "/Users/username/bin/mc/TopoMC/pymclevel/infiniteworld.py", line 1064, in file
  File "/Users/username/bin/mc/TopoMC/pymclevel/infiniteworld.py", line 1058, in <lambda>
IOError: [Errno 24] Too many open files: 'Worlds/TestTown/region/r.0.0.mcr'
--END ERROR--

Which I wonder if this may be coming from there being 1841 files in the Arrays/TestTown folder?

**Comment by mathuin** [comment]
You may have chosen too large a region for those settings.  Try a smaller region (0.05 by 0.05) to see if that works.

When I run ./BuildArrays.py on the BlockIsland test region, I see the pyximport error, but mclevel still loads so I don't _think_ that's a problem.  I see the spam of unknown block values, which _is_ a problem.  Looks like pymclevel changed the way alphaMaterials works to import a YAML file from the current directory -- which fails, of course, because we aren't in pymclevel's directory when we do the import.  So, to work around this problem, copy ../pymclevel/minecraft.yaml to TopoMC's directory and then ./BuildArrays.py should work again.

I will tackle ./BuildWorld.py next. :-)

**Comment by ylluminate** [comment]
In my mc folder I have TopoMC and pymclevel.

While in TopoMC I did a `cp ../pymclevel/minecraft.yaml .` to place it into the TopoMC root folder.

I received the same errors again while attempting to run this:

Import error loading precompiled _nbt extension. Trying pyximport...
Import error loading _nbt extension ImportError('No module named pyximport',)
Traceback (most recent call last):
  File "../pymclevel/nbt.py", line 8, in <module>
    from pyximport import install; install()
ImportError: No module named pyximport
Creating world from region TestTown
--END ERROR--

So it seems as though moving the folder into TopoMC's works vs what you said?...

**Comment by mathuin** [comment]
As long as the checkouts have the same parent -- at home, mine is ~/git -- the software should work.  

The cp command is intended to make ./BuildArrays.py work.  Did you rerun the ./BuildArrays.py command after copying the file?

The pyximport errors are not critical.  Anything from "Trying pyximport..." to "ImportError: No module named pyximport" should not affect your code.  The "Creating world from region TestTown" message is expected.

The test render of Block Island came through fine here.  I am looking at this pyximport stuff to see if there's an installer for Ubuntu as it would be nice for this to be speeded up.

Jack.

**Comment by mathuin** [comment]
codewarrior0 fixed pymclevel so it no longer requires us to copy that file into the TopoMC repository.  If you update your pymclevel checkout, you can delete the minecraft.yaml from the TopoMC checkout.  Yay for that.

Still looking for more information with regard to this pyximport stuff.

Jack.

**Comment by ylluminate** [comment]
Thanks for the updates.  Presently pymclevel seems to work correctly now by simply being in the parent folder.  Notwithstanding after a couple minutes of churning BuildArrays.py starts spewing forth the "WARNING: mcarray: unknown block value: <various block types>".

I'll have to try this on Block Island again momentarily and will update this ticket with results.

**Comment by mathuin** [comment]
You can check to see if your checkout of pymclevel has the updated materials.py by grep'ping for pkg_resources -- if materials.py imports pkg_resources and uses it to retrieve the filename, then you're good.

Jack.

**Comment by ylluminate** [comment]
pwd == pymclevel
`grep -r pkg_resources *` -> No results.

yet if i:
`find . | grep materials.py` -> I see:
./materials.py
./materials.pyc

**Comment by mathuin** [comment]
If that is the case, you'll need to update your pymclevel checkout.  The most recent commit includes the fix.  Executing a "git pull" in that checkout should update materials.py which will get recompiled the next time you run ./BuildArrays.py.

Jack.

**Comment by mathuin** [comment]
Any luck with the checkout update?  I am hoping that you're well on your way to a successful world generation. :-)

Jack.

**Comment by ylluminate** [comment]
Hmm, sorry about that.  Apparently my last post did not actually commit here on GitHub.  I had attempted to explain that:

Indeed, after the update most of the issues were cleared up, however I ran into the following with BuildArrays.py (as you can see something is still amiss):
...
WARNING:mcarray:unknown block value: Water (still)
WARNING:mcarray:unknown block value: Water (still)
WARNING:mcarray:unknown block value: Water (still)
WARNING:mcarray:unknown block value: Water (still)
WARNING:mcarray:unknown block value: Water (still)
WARNING:mcarray:unknown block value: Water (still)
WARNING:mcarray:unknown block value: Water (still)
WARNING:mcarray:unknown block value: Water (still)
WARNING:mcarray:unknown block value: Water (still)
... tiles completed: total array of 9 tiles was 735 x 630
Consider setting spawn point to 512, 48, 595
Land cover statistics (462858 total):
  216310 (46.73%): Deciduous Forest
  123020 (26.58%): Pasture/Hay
  33569 (7.25%): Evergreen Forest
  28216 (6.10%): Grasslands/Herbaceous
  25124 (5.43%): Developed/Open-Space
  13744 (2.97%): Developed/Low-Intensity
  10497 (2.27%): Cultivated Crops
  4483 (0.97%): Developed/Medium-Intensity
  4431 (0.96%): Water
  3326 (0.72%): Shrub/Scrub
  138 (0.03%): Mixed Forest
Tree statistics (7325 total):
  6300 (86.01%): Redwood
  982 (13.41%): Birch
  41 (0.56%): Regular
  2 (0.03%): Shrub
Ore statistics (965209 total nodes, 110842 total veins):
  375163 (20574 veins): Dirt
  227491 (36248 veins): Iron Ore
  189193 (10438 veins): Gravel
  133629 (20503 veins): Coal Ore
  22701 (3605 veins): Gold Ore
  11578 (12964 veins): Redstone Ore
  4150 (4863 veins): Lapis Lazuli Ore
  1304 (1647 veins): Diamond Ore

**Comment by mathuin** [comment]
Oh, embarrassing. :-)  I fixed the 'Water (still)' thing (among others I am sure) in the develop branch but have yet to make a new release since then.  You might want to switch to the develop branch, or replace 'Water (still)' and 'Lava (still)' with 'Water' and 'Lava' in ore.py.

Sorry about that.  Once school is out, I will make a new release.

Jack.

**Comment by ylluminate** [comment]
Jack, got it working!  Really neat.  

Got it loaded up and we explored it quite a bit.  Sadly the translation seems to be missing a lot in our scenario.  The hills are not nearly dramatic enough.  I did think it was interesting how it translated roads and highways into the mix.  That was quite useful.

I don't know what's up with the scale, but it doesn't seem to scale it at all to a workable size.  All of the hills are just tiny bumps (essentially just 1 block level, etc.)  What can be done to make this fit more life like sizes / scales for closer approximation to the real world?

Do you have an email address?  I tried to send you a message on here, but it would not send an email since it says "you don't have one..."  It would be nice to take this topic off thread I think to really hit the finer points.

**Comment by ylluminate** [comment]
Just to give you an idea of how the scale is off, I pulled out the "tape measure" and did some calculations for you to see:  
• http://j.mp/tIGIbZ
• http://j.mp/vzFPS2

You can see that it's quite a ways off.  Even if the ground below would have to be more shallow (perhaps we'd only need about 30 meters / blocks vs the 72 that currently exist below the lowest point around there. But that's neither here nor there really.  I would certainly like to figure out how to get this working more accurately.

From looking at the help, it appears that I can fiddle with the scale values.  I think I'm going to set both scale and vscale to 1  to see what happens, however I'm not certain exactly what the sealevel and maxdepth accomplish.  I'm wondering if the slope option allows for smoother ponds and lakes?  Just no complete clarity on the options.  Right now it takes about an hour and a half to generate the arrays so it's not like I can play too much unless I cut the area down dramatically to test it, however I think some input from you would suffice to get it going in the right direction.

*UPDATE: When I started running the generator it returned the following regarding height: Warning: vertical scale of 1 for region TestRegion is invalid (max elevation is 289, max allowed is 86) -- changed to 4

I have a Mac Pro with 16 cores, since the default setting was not maxing out the processors I went ahead and raised the process level to 64.  Not sure if that will help much, but it is maxing out the processors now.  Interestingly it's been running for about 8.5 hours now.  I sure wish I was able to understand the height issue better and get a handle on that so I'm not having to regenerate again as I will likely have to... :S

**Comment by ylluminate** [comment]
Could we get a feedback on the BuildArrays... ? :>  I've not looked at the code yet, but I would guess we could at least give some kind of indication of which file of total count is processed as I certainly don't like the idea of canceling an operation if it's >50% completed, etc.  I just have no idea of telling how far along the process is and after so long, I think I'm at least going to have to bg the process until I get some work done. LOL.

**Comment by mathuin** [comment]
There is some feedback in there, built around timing, but you need to change the logging threshold.  Check out timer.py (I think that's what it's called) as well as the individual modules (mcarray.py is the one for ./BuildArrays.py IIRC).  I should make that enabled via command-line with --verbose or something.  You probably want to set the process limit to the number of cores, anything more will end up thrashing from what I've seen.  Obviously your mileage may vary.

As for the scaling, yes, they default at 6 for each -- that's six real-world meters for each Minecraft block.  Things get hinky if you try a horizontal scale below 3, because the raw data for landcover is in 30-meter increments and so things get blocky.  The lower limit for useful vertical scale values is related to the maximum elevation and sealevel, but the primary limiting factor here is the completely annoying shortness of Minecraft chunks.  I swear, that's the one thing I want them to change -- give me 4096, or at least 1024, instead of this crap.  Sigh.  Anyway.  The elevation data quality should be fine though I have noticed some wackiness with ND9 data.

Sealevel and maxdepth are pretty straightforward, but I need to reimplement them because changing them can be fragile.  Basically, sealevel is how many Minecraft blocks up from the bottom of the map represents zero meters above sea level.  The game defaults to halfway, but I change it because what nearly all TopoMC users want is elevation above sea level.  Maxdepth represents the maximum depth in Minecraft blocks in open water.  I simulate bathymetry with a very simple algorithm which provides for a smooth slope from sea level down to maxdepth.  Obviously, maxdepth cannot be greater than sealevel.  The slope value should make the slope more steep or more gentle, but it affects the entire map.

My goal for winter break is to refactor the array/world code.  This should allow for sealevel/maxdepth/slope/etc settings to be changed cleanly, and for the code to work in the bravo server as a terrain generator.  

My email address is my github account at gmail.com -- I'll see what I have to do to make it easier for you to send me a message inside github...

Jack.
